# Generated by Django 5.1.6 on 2025-03-05 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_change_book', 'Can change book'), ('can_delete_book', 'Can delete book')]},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
